"""S-16 standards layer — merge order/dedupe/scalar override, cycle + unknown -> exit 2,
deterministic STANDARDS.md via sync (byte-identical re-run, drift detection)."""
import pytest
from typer.testing import CliRunner

from servan.cli.app import app
from servan.config import ConfigError, ProjectConfig, StandardsLoader
from servan.rendering import SyncService

BASE = """\
schema = 1
name = "base"
[principles]
rules = ["fail loud", "deterministic output"]
[testing]
style = "tests-first"
required_before_commit = true
rules = ["acceptance criteria as test names"]
"""

PYTHON = """\
schema = 1
name = "python"
extends = ["base"]
[principles]
rules = ["deterministic output", "pydantic at boundaries"]
[testing]
style = "pytest"
rules = ["fixtures in conftest.py"]
[forbidden]
literals = ["print("]
exclude_paths = ["src/*/cli/*"]
"""


@pytest.fixture
def standards_dir(tmp_path):
    d = tmp_path / "standards"
    d.mkdir()
    (d / "base.toml").write_text(BASE)
    (d / "python.toml").write_text(PYTHON)
    return d


def test_merge_order_concat_dedupe_and_scalar_override(standards_dir):
    merged = StandardsLoader(standards_dir).load("python")
    assert merged.sections["principles"]["rules"] == [
        "fail loud", "deterministic output", "pydantic at boundaries"]
    assert merged.sections["testing"]["style"] == "pytest"               # child wins
    assert merged.sections["testing"]["required_before_commit"] is True  # inherited
    assert merged.sections["testing"]["rules"] == [
        "acceptance criteria as test names", "fixtures in conftest.py"]
    assert merged.sections["forbidden"]["literals"] == ["print("]        # new section


def test_project_list_merge_left_to_right(standards_dir):
    (standards_dir / "strict.toml").write_text(
        'schema = 1\nname = "strict"\n[testing]\nstyle = "mutation"\n')
    merged = StandardsLoader(standards_dir).load_all(["python", "strict"])
    assert merged.sections["testing"]["style"] == "mutation"             # later wins
    assert merged.sections["principles"]["rules"][0] == "fail loud"      # still based


def test_cycle_detection(standards_dir):
    (standards_dir / "a.toml").write_text('schema = 1\nname = "a"\nextends = ["b"]\n')
    (standards_dir / "b.toml").write_text('schema = 1\nname = "b"\nextends = ["a"]\n')
    with pytest.raises(ConfigError, match="cycle"):
        StandardsLoader(standards_dir).load("a")


def test_unknown_standard_names_the_fix(standards_dir):
    with pytest.raises(ConfigError, match="unknown standard 'nope'.*base"):
        StandardsLoader(standards_dir).load("nope")


def test_project_config_gains_standards():
    cfg = ProjectConfig.model_validate({"standards": ["base", "python"]})
    assert cfg.standards == ("base", "python")
    assert ProjectConfig().standards == ()


def test_cli_list_and_show(standards_dir, tmp_path):
    runner = CliRunner()
    result = runner.invoke(app, ["--config-dir", str(tmp_path), "standards", "list"])
    assert result.exit_code == 0 and result.output.splitlines() == ["base", "python"]
    result = runner.invoke(app, ["--config-dir", str(tmp_path), "standards", "show", "python"])
    assert result.exit_code == 0
    assert result.output.index("fail loud") < result.output.index("pydantic at boundaries")
    result = runner.invoke(app, ["--config-dir", str(tmp_path), "standards", "show", "nope"])
    assert result.exit_code == 2


def test_sync_writes_standards_md_byte_identical(cfg_dir, project):
    (cfg_dir / "standards").mkdir()
    (cfg_dir / "standards" / "base.toml").write_text(BASE)
    (cfg_dir / "standards" / "python.toml").write_text(PYTHON)
    (project / ".servan.toml").write_text(
        'profile = "test"\nstandards = ["base", "python"]\n')
    SyncService().sync(project)
    target = project / "STANDARDS.md"
    first = target.read_text()
    assert first.startswith("<!-- GENERATED by servan sync from standards: base, python")
    assert "fail loud" in first and "style: pytest" in first
    SyncService().sync(project)
    assert target.read_text() == first                                   # deterministic


def test_sync_check_detects_standards_drift_without_writing(cfg_dir, project):
    (cfg_dir / "standards").mkdir()
    (cfg_dir / "standards" / "base.toml").write_text(BASE)
    (project / ".servan.toml").write_text('profile = "test"\nstandards = ["base"]\n')
    SyncService().sync(project)
    target = project / "STANDARDS.md"
    target.write_text("stale")
    drifted = [r for r in SyncService().sync(project, check=True)
               if r.path.name == "STANDARDS.md"]
    assert len(drifted) == 1 and drifted[0].changed
    assert target.read_text() == "stale"                                 # check writes nothing


def test_no_standards_no_standards_md(cfg_dir, project):
    results = SyncService().sync(project)
    assert all(r.path.name != "STANDARDS.md" for r in results)
    assert not (project / "STANDARDS.md").exists()
