import pytest
pytestmark = pytest.mark.skip(reason="S-07: unskip when implementing `servan lint`")

def test_valid_page_passes(): ...
def test_missing_okf_key_fails(): ...
def test_broken_link_target_exit3(): ...
def test_orphan_detection_excludes_index_log_status(): ...
def test_superseded_still_linked_as_current(): ...
