"""S-12 dogfood — this repo itself runs on servan: wiki/ lints clean and the
generated status page is committed."""
import pathlib

from servan.lint import LintEngine, Severity

ROOT = pathlib.Path(__file__).resolve().parents[1]


def test_repo_wiki_lints_without_errors():
    findings = LintEngine().run(ROOT)
    errors = [f for f in findings if f.severity is Severity.ERROR]
    assert errors == [], "\n".join(f"{f.rule}: {f.path}: {f.message}" for f in errors)


def test_okf_reserved_and_generated_files_exist():
    assert (ROOT / "wiki" / "index.md").is_file()
    assert (ROOT / "wiki" / "log.md").is_file()
    assert (ROOT / "wiki" / "status.md").is_file()  # generated by `servan status`
