"""StandardsRenderer — projects the merged standards stack into generated STANDARDS.md."""
from __future__ import annotations

import pathlib
from collections.abc import Sequence

from ..config.global_config import GlobalConfig
from ..config.project_config import ProjectConfig
from ..config.standards_loader import StandardsLoader
from ..config.standards_set import StandardsSet
from ..logging_setup import get_logger
from ..team.resolver import Team
from .base import Renderer, RenderResult

_log = get_logger("rendering.standards")

HEADER = "<!-- GENERATED by servan sync from standards: {names} — edit the TOML, not this file -->"


def render_standards_md(standard: StandardsSet, names: Sequence[str]) -> str:
    """Deterministic markdown projection; also used by `servan standards show`."""
    lines = [HEADER.format(names=", ".join(names)), "", "# Standards", ""]
    for section, values in standard.sections.items():
        lines += [f"## {section}", ""]
        for field, value in values.items():
            if isinstance(value, list):
                lines.extend(f"- {rule}" for rule in value)
            else:
                lines.append(f"{field}: {str(value).lower() if isinstance(value, bool) else value}")
        lines.append("")
    return "\n".join(lines)


class StandardsRenderer(Renderer):
    def __init__(self, loader: StandardsLoader) -> None:
        self._loader = loader

    def render(self, team: Team, config: GlobalConfig, project: ProjectConfig,
               root: pathlib.Path, *, check: bool = False) -> list[RenderResult]:
        if not project.standards:
            return []
        desired = render_standards_md(self._loader.load_all(project.standards), project.standards)
        path = root / "STANDARDS.md"
        summary = f"standards: {', '.join(project.standards)}"
        if check:
            changed = not path.exists() or path.read_text(encoding="utf-8") != desired
            _log.info("check %s: %s", path, "drift" if changed else "in sync")
            return [RenderResult(path=path, summary=summary, changed=changed)]
        path.write_text(desired, encoding="utf-8")
        _log.info("wrote %s", path)
        return [RenderResult(path=path, summary=summary)]
